# Generated by Django 4.2.7 on 2024-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_lesson_userprogress_userpoints_sign_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='lesson_videos', to='app1.video'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='quiz_videos', to='app1.video'),
        ),
    ]
