# Generated by Django 5.0.1 on 2024-01-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_video_user_is_active_lesson_videos_quiz_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='lesson',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_answers/'),
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
