# Generated by Django 5.0.1 on 2024-02-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_userprogress_lesson_remove_userprogress_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='videos',
        ),
    ]
