# Generated by Django 5.0.1 on 2024-02-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_quizcompletion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
