# Generated by Django 5.0.1 on 2024-02-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
